version: '3.7'

services:
  namenode:
    image: dockerhub.datagrand.com/yskg/hadoop-namenode:2.7.7
    hostname: namenode
    networks:
      - bdp
    volumes:
    #  - namenode:/hadoop/dfs/name
      - ./volume/hadoop/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./volume/hadoop/hadoop.env
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  datanode1:
    image: dockerhub.datagrand.com/yskg/hadoop-datanode:2.7.7
    hostname: datanode1
    networks:
      - bdp
    volumes:
    #  - datanode1:/hadoop/dfs/data
      - ./volume/hadoop/datanode1:/hadoop/dfs/data
    env_file:
      - ./volume/hadoop/hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  datanode2:
    image: dockerhub.datagrand.com/yskg/hadoop-datanode:2.7.7
    hostname: datanode2
    networks:
      - bdp
    volumes:
    #  - datanode2:/hadoop/dfs/data
      - ./volume/hadoop/datanode2:/hadoop/dfs/data
    env_file:
      - ./volume/hadoop/hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  resourcemanager:
    image: dockerhub.datagrand.com/yskg/hadoop-resourcemanager:2.7.7
    hostname: resourcemanager
    networks:
      - bdp
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075"
    env_file:
      - ./volume/hadoop/hadoop.env
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true

  historyserver:
    image: dockerhub.datagrand.com/yskg/hadoop-historyserver:2.7.7
    networks:
      - bdp
    volumes:
    #  - historyserver:/hadoop/yarn/timeline
      - ./volume/hadoop/historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 resourcemanager:8088"
    env_file:
      - ./volume/hadoop/hadoop.env
    deploy:
      endpoint_mode: dnsrr
    healthcheck:
      disable: true

  nodemanager1:
    image: dockerhub.datagrand.com/yskg/hadoop-nodemanager:2.7.7
    hostname: nodemanager1
    networks:
      - bdp
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 resourcemanager:8088"
    env_file:
      - ./volume/hadoop/hadoop.env
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true

  nodemanager2:
    image: dockerhub.datagrand.com/yskg/hadoop-nodemanager:2.7.7
    hostname: nodemanager2
    networks:
      - bdp
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode1:50075 datanode2:50075 resourcemanager:8088"
    env_file:
      - ./volume/hadoop/hadoop.env
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true
 
#volumes:
#  namenode:
#  datanode1:
#  datanode2:


networks:
  bdp: 
    external: true
    name: bdp


