version: '3.7'

services:
  proxyer:
    image:  nginx:latest
    hostname: proxyer
    ports:
      - 50072:50070
      - 8086:8088
    deploy:
      endpoint_mode: vip
    depends_on:
      - namenode
    volumes:
      - ./config/hadoop.conf:/etc/nginx/conf.d/hadoop.conf
    networks:
      - hadoop

  namenode:
    image: dockerhub.datagrand.com/yskg/hadoop-namenode:2.7.7-alpine
    hostname: namenode
    networks:
      - hadoop
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./hadoop.env
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  datanode:
    image: dockerhub.datagrand.com/yskg/hadoop-datanode:2.7.7-alpine
    hostname: datanode
    networks:
      - hadoop
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  resourcemanager:
    image: dockerhub.datagrand.com/yskg/hadoop-resourcemanager:2.7.7-alpine
    hostname: resourcemanager
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true

  nodemanager:
    image: dockerhub.datagrand.com/yskg/hadoop-nodemanager:2.7.7-alpine
    hostname: nodemanager
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  historyserver:
    image: dockerhub.datagrand.com/yskg/hadoop-historyserver:2.7.7-alpine
    networks:
      - hadoop
    volumes:
      - historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      endpoint_mode: dnsrr

volumes:
  datanode:
  namenode:
  historyserver:


networks:
  hadoop: 
    external: true
    name: hadoop
