version: '3.7'

services:
  proxyer:
    image:  nginx:latest
    hostname: proxyer
    ports:
      - 50071:9000
      - 8089:8088
    deploy:
      replicas: 1
      endpoint_mode: vip
    #environment:
    #  JVMFLAGS: -Xms1024m -Xmx1024m
    depends_on:
      - namenode
    volumes:
      - ./config/hadoop.conf:/etc/nginx/conf.d/hadoop.conf
      - ./config/yarn.conf:/etc/nginx/conf.d/yarn.conf
    networks:
      - hadoop

  namenode:
    image: datagrand/hadoop-namenode:3.1.3
    hostname: namenode
    networks:
      - hadoop
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      #restart_policy:
      #  condition: on-failure
      #labels:
      #  traefik.docker.network: hadoop
      #  traefik.port: 50070
    healthcheck:
      disable: true

  datanode:
    image: datagrand/hadoop-datanode:3.1.3
    hostname: datanode
    networks:
      - hadoop
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      #mode: global
      replicas: 1
      endpoint_mode: dnsrr
      #restart_policy:
      #  condition: on-failure
      #labels:
      #  traefik.docker.network: hadoop
      #  traefik.port: 50075
    healthcheck:
      disable: true

  resourcemanager:
    image: datagrand/hadoop-resourcemanager:3.1.3
    hostname: resourcemanager
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
      #restart_policy:
      #  condition: on-failure
      #labels:
      #  traefik.docker.network: hadoop
      #  traefik.port: 8088
    healthcheck:
      disable: true

  nodemanager:
    image: datagrand/hadoop-nodemanager:3.1.3
    hostname: nodemanager
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      #mode: global
      replicas: 1
      endpoint_mode: dnsrr
      #restart_policy:
      #  condition: on-failure
      #labels:
      #  traefik.docker.network: hadoop
      #  traefik.port: 8042
    healthcheck:
      disable: true
  

volumes:
  datanode:
  namenode:
  hadoop_historyserver:


networks:
  hadoop: 
    external: true
    name: hadoop
