version: '3'
services:
  base:
    build: ./base
    image: datagrand/hadoop-base:3.1.3
  
  base1:
    build: ./base1
    image: bde/hadoop-base1:3.1.3
  
  namenode:
    build: ./namenode
    image: datagrand/hadoop-namenode:3.1.3

  datanode:
    build: ./datanode
    image: datagrand/hadoop-datanode:3.1.3
  
  resourcemanager:
    build: ./resourcemanager
    image: datagrand/hadoop-resourcemanager:3.1.3
  
  nodemanager:
    build: ./nodemanager
    image: datagrand/hadoop-nodemanager:3.1.3
