version: '3'
services:
  base:
    build: ./base
    image: datagrand/hbase-base:2.1.10
  
  standalone:
    build: ./standalone
    image: ${PROJECT_PREFIX}/hbase-standalone:2.1.10
  
  hmaster:
    build: ./hmaster
    image: ${PROJECT_PREFIX}/hbase-hmaster:2.1.10

  hregionserver:
    build: ./hregionserver
    image: ${PROJECT_PREFIX}/hbase-hregionserver:2.1.10
  